import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  meta: [
    { 'http-equiv': 'x-ua-compatible', content: 'IE=edge' },
    { name: 'format-detection', content: 'telephone=no' },
    { name: 'color-scheme', content: 'light dark' },
    { name: 'grammarly', content: 'no' }
  ]
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`antialiased ${inter.className}`} suppressHydrationWarning>
          <Header />
          <main className="pt-16"> {/* Adjust pt-16 based on Header height */}
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}